:sparkles: M1 Mac にて Serverless Framework の開発環境を行える Docker 環境を作成する
DynamoDB Local が M1 Mac に対応していないため Serverless Framework の開発環境を Docker で行うようにする。
まずは Serverless Framework の開発で使用している Node.js と Python が動くものを構築するため、マルチステージングビルドを使用して Node.js と Python のイメージから Node.js と Python だけを抜き出し ubuntu のイメージに移植する。

＜Node.js の移植＞
Yarnも使えるようにさせるため、Yarn の移植を行っている。
なぜ以下のような処理が必要なのかは Node.js の公式の Dockerfile で行っていることをそのまま移植してきている。

```dockerfile
COPY --from=node /opt/yarn* /opt/yarn
RUN ln -fs /opt/yarn/bin/yarn /usr/local/bin/yarn && \
    ln -fs /opt/yarn/bin/yarnpkg /usr/local/bin/yarnpkg
```

詳しくはこちらのリンクを確認してください。

https://github.com/nodejs/docker-node/blob/652749b5246f304bf5913ce458755ac003b7c3dc/17/buster/Dockerfile#L61

＜Python の移植＞
python:xx.xx.xx-buster の image を使うことで ARM 版に対応している image を使用する。
下記の処理を追加しないと「libexpat.so.1: cannot open shared object file: No such file or directory」というエラーが表示され Python が使用することができなかった。

```dockerfile
COPY --from=python /lib/aarch64-linux-gnu/libexpat.so.1 /usr/lib/aarch64-linux-gnu/libexpat.so.1
```

また Python の依存関係をインストールする時に ca-certificates をインストールしておかないと以下のようなエラーがでるため、apt-install ca-certificates でインストールしておく。

```shell
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/boto3/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/boto3/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/boto3/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/boto3/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/boto3/
Could not fetch URL https://pypi.org/simple/boto3/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/boto3/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement boto3==1.21.0
ERROR: No matching distribution found for boto3==1.21.0
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
```

これは番外編だが、なんか微妙に動かない事象があってもしかしたら以下の記述も必要かも？
エラーとしては「python: error while loading shared libraries: libpython3.9.so.1.0: cannot open shared object file: No such file or directory」こんなエラーがでるかもしれない。

```dockerfile
COPY --from=python /usr/local/lib/libpython*.*.so.1.0 /usr/lib/aarch64-linux-gnu/
```